import Head from 'next/head'
import Layout from '../components/layout'
import About from '../components/About'
import Works from '../components/Works'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className='bg-[#212121]'>
      <Head>
        <title>Miguel Guell | PORTFOLIO</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Works />
      </Layout>
    </div>
  )
}
