import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

export default function Home() {
  return (
    <div class>
      <Head>
        <title>Miguel Guell | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>
      <Layout>

      </Layout>
    </div>
  )
}
