import Head from 'next/head'
import Layout from '../components/layout'
import About from '../components/About'
import Works from '../components/Works'
import Hero from '../components/Hero'
import Separation from '../components/Separation'

export default function Home() {
  return (
    <>
      <Head>
        <title>Miguel Guell | PORTFOLIO</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
        <Hero />
        <div className='w-full sm:px-1'>
          <About />
          <Separation />
          <Works />
        </div>
      </Layout>
    </>
  )
}
